//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "chapters")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub wordbook_id: i32,
    pub name: String,
    pub sort_order: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wordbooks::Entity",
        from = "Column::WordbookId",
        to = "super::wordbooks::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Wordbooks,
    #[sea_orm(has_many = "super::words::Entity")]
    Words,
}

impl Related<super::wordbooks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wordbooks.def()
    }
}

impl Related<super::words::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Words.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
