//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "word_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub word_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tags::Entity",
        from = "Column::TagId",
        to = "super::tags::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tags,
    #[sea_orm(
        belongs_to = "super::words::Entity",
        from = "Column::WordId",
        to = "super::words::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Words,
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tags.def()
    }
}

impl Related<super::words::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Words.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
