//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "words")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub chapter_id: i32,
    pub source: String,
    pub translation: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    pub sort_order: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chapters::Entity",
        from = "Column::ChapterId",
        to = "super::chapters::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Chapters,
    #[sea_orm(has_many = "super::word_tags::Entity")]
    WordTags,
}

impl Related<super::chapters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chapters.def()
    }
}

impl Related<super::word_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WordTags.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::word_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::word_tags::Relation::Words.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
